language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: qkeeGFk03fYd28+8dPxq+otTPzY/MUgpEfzcdEeRbCv5StrRPhNgLOMFYh4sNU+y254OjC3zlBRnXfGDv8/4CNlYk9Y4apk1CqkQbDofpx9ejpwhIR/WbScDPmkby/cgMN8UpyjZRwsAoLkwYfEbegAvj6BDPHodsGuogPk7plvxhaoVAtaOXQy/HVPtZ+UHz9WNxjDzTYjc3jvA2EDMiFALCLn2u2srEvH2gscEgkmuKBjvybmOQbixnRNXqhpV0MCb6vvTsADdpt2wTXOM4Lio5jvm5wsFPNaIsM7bkWFvlrsOpuOZyIh6+8nqJYEp81ILu/MuYIXUOZZ+8XD9Nx/Fl+seoCUVMzYps4t3SWeO54I28dFYcIvCSagtqBDtimrIV8CNWX6KyyXlB9ar8ZksUKT/DIO3Lu3XMefPDEWCtyryzsN4zrho14AJ4zOdl9GXbc3Sm85p0mkir3xV5p//CzolRFrrafV9V6MKgZSli2B8CO+FauBauMzqs7oropwKIo/IKJvz9VSpPD2szCD1cIO1ruKzzxuQbrjVIgRtllEaESLYQske4egTxuUFssKRTL+WS9C/Nre0haBlOHpIrWYIdILphgE78SKr3fynjcizAjwv5rcCGY//K9hfbX4TC+pK8pUVAJXTrhkRmEfaChATCKL24jeTaBOtGB8=
  - secure: Hg4cx7Fnw3uTbqQ7T1l8HecODaGDBdgs6m8QJDCKyb+rmXJ/uF/ejFwr7QG4NFy73MknE/TWOi3f4RghSsW0jVWIo05/E3LuKGsDdk5HnmB7j/X4Vdta+yri1Hg+PoEpuw4EFwcg3NeknMTngtk897ssZ+OucNtAwu4ref7Ekfc7las1NfgT2c7UQ4ZqpNameR4iKt62tWyPKSNAMh4YU2EBTVaDxNFecV5egSwgttFtTtPDiVVtYqSUFfqcVZ/+lMiUwPUqhAf/WI/wAwx9SkhWfrgPmeCFrxk/CDyjuhKgw4l9jkdDg4KEPa9VDOR+B21XvStKOONqGfdpxvs2Cgo7mrbCKeaXOji2mUOTfikn83wB574DEFqwFqqMYZAWJ/WCyADEgAY6za5BY8pHjDY5yKYLdCEzjIdJxcvT5M3EOzn2SI79fkCedazg0GVmQxpc51HrVarF79yjAIYr56WV5iyRJsFJ/CeTYOEr4qU/g5vQW8KG/5h94ZbYUwwSYDUyFNQ7kdR7kCKvUFlEDkjzXSGRRb6Q9lwRCnC7ATLd3Z5+fq923iTLkjbslXblW1ftlcqVS4RTtYv2dhhFeVjStpZxGmDk17OX/W6nUgmplljBUjvqJn+qE8L+3win0cg4UCmEHOG03oGBxmK9gVE85d4KTiHpcad9/A9yhmM=
